server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkme?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linkme.backend.module

jwt:
  secret: change_this_secret_to_a_strong_one_change_this_secret
  expire-seconds: 86400

logging:
  level:
    root: INFO
